-- In-Class Exercises
-- Please use the "company_employees_plus.db" database to answer all questions.

/*
Breakdown the number of people by gender who work for a company with more than
1 person in the set, and who's total_worth is more than 5% over the average of
all employees.
*/



/*
Produce a dataset of all employees who are management, female, and have a higher
than country average worth. Include in this dataset the id, name, and email address
of the employees, and sort the list in order by last name.
*/
